name: Rust

on:
  push:
    branches: [ {{branch}} ]
  pull_request:
    branches: [ {{branch}} ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: cargo check
        run: {{check}}

      - name: cargo build
        run: {{build}}

      - name: cargo test
        run: {{test}}

      - name: rustfmt
        run: {{fmt}}

      - name: clippy
        run: {{clippy}}
